/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./public/models/Card/h3xCard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Matte Metallic Paint.002']}
        position={[0.138, 0, -0.026]}
        rotation={[0, 0, -Math.PI]}
        scale={[-9.978, -6.21, -0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[0.138, 0, 0.248]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={-2.809}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials['Material.004']}
        position={[0.138, 0, -0.187]}
        rotation={[-1.571, 0, 0]}
        scale={-4.583}
      />
    </group>
  )
}

useGLTF.preload('./public/models/Card/h3xCard.glb')

